#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the countApplesAndOranges function below.
def countApplesAndOranges(s, t, a, b, apples, oranges):
    count=0
    apples=[apples[i]+a for i in range(len(apples))]
    oranges=[oranges[i]+b for i in range(len(oranges))]
    count_of_apple=len([i for i in range(len(apples))if apples[i]>=s and apples[i]<=t])
    count_of_oranges=len([i for i in range(len(oranges))if oranges[i]>=s and oranges[i]<=t])
    print(count_of_apple)
    print(count_of_oranges)
    

if __name__ == '__main__':
    st = input().split()

    s = int(st[0])

    t = int(st[1])

    ab = input().split()

    a = int(ab[0])

    b = int(ab[1])

    mn = input().split()

    m = int(mn[0])

    n = int(mn[1])

    apples = list(map(int, input().rstrip().split()))

    oranges = list(map(int, input().rstrip().split()))

    countApplesAndOranges(s, t, a, b, apples, oranges)
