#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the breakingRecords function below.
def breakingRecords(scores):

    maxX=scores[0]
    minX=scores[0]
    
    max_count=0
    min_count=0
    for i in range(len(scores)):
        if scores[i]>maxX:
            maxX=scores[i]          
            max_count=max_count+1
        elif scores[i]<minX:          
            minX=scores[i]
            min_count=min_count+1
    return max_count,min_count

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    scores = list(map(int, input().rstrip().split()))

    result = breakingRecords(scores)

    fptr.write(' '.join(map(str, result)))
    fptr.write('\n')

    fptr.close()
