#!/bin/python3

import math
import os
import random
import re
import sys

#
# Complete the 'diagonalDifference' function below.
#
# The function is expected to return an INTEGER.
# The function accepts 2D_INTEGER_ARRAY arr as parameter.
#

def diagonalDifference(arr):
    lft_dgnlSum=sum([arr[i][i] for i in range(3)])
    revarr=arr[::-1]
    ryt_dgnlSum=sum([revarr[i][i] for i in range(3)])
    Dgnldiff=int(lft_dgnlSum) - int(ryt_dgnlSum)
    if Dgnldiff>=0:
        return Dgnldiff
    else:
        return -Dgnldiff

if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input().strip())

    arr = []

    for _ in range(n):
        arr.append(list(map(int, input().rstrip().split())))

    result = diagonalDifference(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
