#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the plusMinus function below.
def plusMinus(arr):
    PstvNum,NgtvNum,zero=0,0,0
    totalEle=len(arr)

    for i in range(totalEle):
        if arr[i]>0:
            PstvNum=PstvNum+1
        elif arr[i]<0:
            NgtvNum=NgtvNum+1
        else:
            zero=zero+1
    print(PstvNum/totalEle)
    print(NgtvNum/totalEle)
    print(zero/totalEle)


if __name__ == '__main__':
    n = int(input())

    arr = list(map(int, input().rstrip().split()))

    plusMinus(arr)
